# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bicicleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('cor', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=100)),
                ('situacao', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('endereco', models.CharField(max_length=60)),
                ('telefone', models.CharField(max_length=15)),
                ('codigo', models.CharField(max_length=10)),
                ('funcao', models.CharField(max_length=40)),
            ],
        ),
    ]
