# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 22:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('BMX', 'BMX'), ('FRONTIER', 'FRONTIER WIN'), ('FOX', 'FOX'), ('ONIX', 'ONIX VB')], max_length=30)),
                ('disponivel', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('endereco', models.CharField(max_length=60)),
                ('telefone', models.CharField(help_text='(99)99999-9999', max_length=14)),
                ('codigo', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaosocial', models.CharField(max_length=40)),
                ('cnpj', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('endereco', models.CharField(max_length=60)),
                ('telefone', models.IntegerField(help_text='(99)99999-9999', max_length=14)),
                ('codigo', models.IntegerField()),
                ('funcao', models.CharField(max_length=40)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_created=True)),
                ('data_retirada', models.DateTimeField(auto_now_add=True)),
                ('bicicleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bicicleta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Funcionario')),
            ],
        ),
    ]
