# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
