# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bicicleta',
            new_name='Ficicleta',
        ),
    ]
