# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160908_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicicleta',
            name='situacao',
        ),
    ]
