# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_bicicleta_situacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaosocial', models.CharField(max_length=40)),
                ('cnpj', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='situacao',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(help_text='(99)99999-9999', max_length=14, verbose_name='Celular'),
        ),
    ]
